### ISSUE TITLE
Different colours for storage, memory and stack variables

### ISSUE THREAD

**Issue by chriseth** [ethereum/mix#108]
The fact whether a variable is a value-type, stored in storage or memory often makes a huge difference. Similar to how other IDEs highlight variables depending on whether they are local variables or class members, Mix could make that distinction clear to the programmer.

Credit for the idea goes to @LianaHus

**Comment by yann300** [comment]
we should also add warning in case of bad declaration
see this issue https://github.com/ethereum/mix/issues/291
