### ISSUE TITLE
UI does not scale well on 4k monitor

### ISSUE THREAD

**Issue by ThePiachu** [ethereum/mix#109]
I tried using Mix on a 4k monitor on Windows and it doesn't scale properly - it's tiny:

![image](https://cloud.githubusercontent.com/assets/964559/10922219/d23926f4-822e-11e5-96d8-f7c2986f73c3.png)

Can you try making the UI scale proportional to the Windows Display settings - https://www.thurrott.com/windows/windows-10/4597/windows-10-feature-focus-display-scaling ?

**Comment by yann300** [comment]
now it should be better if you pull from the develop branch.
