### ISSUE TITLE
Scenario does not update gas

### ISSUE THREAD

**Issue by chriseth** [ethereum/mix#144]
If the source code is changed so that it uses more gas (but the function name still stays the same), the scenario is not updated leading to out-of-gas.
It might be that this only happens for the "manual gas" situation, but then the "automatic gas" should be the default.

**Comment by whatsdis** [comment]
is this why I can't go forward with the Ratings tutorial? it says 'block gas limit reached'

**Comment by yann300** [comment]
moved https://github.com/ethereum/remix/issues/92
