### ISSUE TITLE
mix depends on Qt 5.5 (or latest) but does not report an error with lower qt versions

### ISSUE THREAD

**Issue by winsvega** [ethereum/mix#181]
It appears that on windows webthree-helpers installs qt5.4.1 by default,
To my discovery Mix has issues with qt5,4,1 and does not work properly. (e.g unable to create project)

Mix should at least print notification message that it does not support specific qt version and could not work properly.

**Comment by chriseth** [comment]
Confirmed on linux.

**Comment by yann300** [comment]
@winsvega could you reproduce this bug with qt 5.4.1 and creating a project?
