### ISSUE TITLE
Running Mix in a VM

### ISSUE THREAD

**Issue by liorsaar1** [ethereum/mix#185]
As a user, I would like to run Mix in a vagrant/vb/x11 vm, since it doesn't build on mac osx 10.11.
This will require replacing the `libgl1-mesa-dev` dependency with `libgl1-mesa-swx11`.
Any pointers on how I can do this myself will be appreciated.

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
