### ISSUE TITLE
Mix crash when click on  "copy to clipboard"

### ISSUE THREAD

**Issue by winsvega** [ethereum/mix#208]
If I close the project then go Help->About 
there is strange copy-like button left next to close button.
If I click it, Mix crash.

**Comment by winsvega** [comment]
confirmed this bug happens on debug build but not in release

**Comment by winsvega** [comment]
the error seems to be in JSON.stringify

**Comment by LianaHus** [comment]
we have unpredictable crash on "copy to clipboard" button not only on about dialog. still can't reproduce

**Comment by winsvega** [comment]
this bug happens after closing a project 
and seems to be only in Debug mod

related
https://github.com/ethereum/mix/issues/255

it is something about cliboard object. Probably null or corrupt address.
it throws on CopyButton.qml

```
onClicked:
{
        clipboard.text = getContent()
}
```

getContent() function is ok,

**Comment by JeffreyBPetersen** [comment]
Also getting sporadic crashes on copying to clipboard, both within and outside the editor while it's open.
