### ISSUE TITLE
Mix.exe has stopped working

### ISSUE THREAD

**Issue by deskenny** [ethereum/mix#211]
![image](https://cloud.githubusercontent.com/assets/5212629/12901546/37981baa-ceb4-11e5-83fa-e0884e2dd80a.png)

steps to reproduce
1. launch mix
2. select 'deploy->open compilation result

version 1.0.0
solidity 0.2.1
windows 10

**Comment by bellaj** [comment]
is there a stable release without this problem?
is it caused by a graphical issue or what?

**Comment by bobsummerwill** [comment]
Mix has been retired, I am afraid, @bellaj, so this issue will never be addressed.

See https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/.

And some alternatives listed at http://solidity.readthedocs.org
