### ISSUE TITLE
1.1.3 and 1.1.2 both crash on Mac (latest El Capitan)

### ISSUE THREAD

**Issue by davidhq** [ethereum/mix#223]
Mix doesn't even start - crashes few seconds after start...

Here is the crash report: http://cl.ly/3t1k3y0z1D1P
(or http://cl.ly/3t1k3y0z1D1P/Mix_2016-02-12-153717_eclipse.crash)

**Comment by bobsummerwill** [comment]
Closed as dupe of "The Heisenbug" - https://github.com/ethereum/webthree-umbrella/issues/565.   We can reopen if we later find there is anything unique here.
