### ISSUE TITLE
Unable to remove Tx's while code not compiled successfully

### ISSUE THREAD

**Issue by JohnDorien1** [ethereum/mix#252]
I might want to remove e.g. the sample.sample contract tx, but cannot if I already removed the sample code and created new one that does not compile due to errors. This creates a series of issues afterwards, e.g. the previous issue #251.

The workflow "first delete the tx and then change the code" is not the requested solution here

**Comment by yann300** [comment]
it should be removed by:
- right click on the transaction and "remove"
- press "suppr"

**Comment by JohnDorien1** [comment]
I can do right click and remove. But checking the little button next to Tx and "reload" is not possible.

**Comment by yann300** [comment]
To fix this: avoid rebuilding and warn the user when a tx refers to a contract that no longer exists in the code editor

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
