### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by delta575** [ethereum/mix#254]
Freezes on start

`Qt: Untested Windows version 10.0 detected!

WARNING: This project is using the experimental QML API extensions for QtWebEngine and is therefore tied to a specific QtWebEngine release.
WARNING: The experimental API will change from version to version, or even be removed. You have been warned!

QtWebEngineProcess not found at location C:/Program Files/Ethereum/bin\QtWebEngineProcess.exe. Trying fallback path...
Layout must be attached to Item elements
Layout must be attached to Item elements
qml: [{"id":0,"jsonrpc":"2.0","method":"eth_accounts","params":[]}]
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_server_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_server_method
qt.network.ssl: QSslSocket: cannot resolve SSL_select_next_proto
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
qrc:/QtQuick/Controls/ScrollView.qml:232:9: QML Binding: Binding loop detected for property "value"
qrc:/QtQuick/Controls/ScrollView.qml:225:9: QML Binding: Binding loop detected for property "value"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
  i  00:13:04.782|main  Killing blockchain & extras database (WithExisting::Kill).
  i  00:13:04.798|main  Killing state database (WithExisting::Kill).
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
qml: [{"id":0,"jsonrpc":"2.0","method":"eth_accounts","params":[]}]
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
  i  00:13:04.838|main  Killing blockchain & extras database (WithExisting::Kill).
  i  00:13:04.851|main  Killing state database (WithExisting::Kill).
  i  00:13:04.885|main  Killing blockchain & extras database (WithExisting::Kill).
  i  00:13:04.900|main  Killing state database (WithExisting::Kill).
qml: Closing project
qml: Loading project at file://C:/Users/Felipe/prueba
qrc:///QtQuick/Controls/Private/ScrollBar.qml:98:46: Unable to assign [undefined] to bool
qrc:///QtQuick/Controls/Private/ScrollBar.qml:98:46: Unable to assign [undefined] to bool
qrc:/QtQuick/Controls/TextArea.qml:728:24: Unable to assign [undefined] to QColor
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot read property '__contentHeight' of null
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot read property '__contentHeight' of null
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:72:42: Unable to assign TextArea_QMLTYPE_66 to TextField_QMLTYPE_53
qrc:///QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read property of null
qrc:///QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read property of null
  i  00:13:05.017|main  Killing blockchain & extras database (WithExisting::Kill).
  i  00:13:05.032|main  Killing state database (WithExisting::Kill).
Waiting for current execution to complete
  i  00:13:06.269|<unknown>  Decreasing DB node ref count below zero with no DB node. Probably have a corrupt Trie. #84acdce9ÔÇª
  i  00:13:06.283|<unknown>  Decreasing DB node ref count below zero with no DB node. Probably have a corrupt Trie. #a71b164eÔÇª`

**Comment by chriseth** [comment]
@yann300 please close if it is a duplicate. If the log adds information to the original bug, please copy the log.
