### ISSUE TITLE
Mix freezes when .mix of current project is deleted

### ISSUE THREAD

**Issue by JohnDorien1** [ethereum/mix#255]
When deleting the .mix file of the last open project and then open mix, it will produce following notices and freeze. Ubuntu 14.04. Low priority bug i would think. Might not be daily case to delete a .mix file, but mix should probably throw a user dialog error instead of freezing / crashing.

```
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Private/ScrollBar.qml:98:46: Unable to assign [undefined] to bool
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Private/ScrollBar.qml:98:46: Unable to assign [undefined] to bool
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/TextArea.qml:728:24: Unable to assign [undefined] to QColor
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot read property '__contentHeight' of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot read property '__contentHeight' of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/TextFieldStyle.qml:72:42: Unable to assign TextArea_QMLTYPE_114 to TextField_QMLTYPE_47
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read property of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read property of null
```

**Comment by winsvega** [comment]
Mix is failing on mix/moc_Clipboard.cpp line 169.
when emmiting signal clibboardChanged. 

I found this happen when I ctrl+x or ctrl+c any\* file after creating a new project
*any file located at newly created project folder or one level upwards. 

if I ctrl+x/ctrl+c a file that is located at sibling folder or two levels upwards everything is fine and then I could ctrl+c, ctrl+x files from project directory without any errors.

**Comment by yann300** [comment]
is this happening only in debug?

**Comment by winsvega** [comment]
yes
deleting .mix does not result in crash. mix would just open homepage (new project / load)

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
