### ISSUE TITLE
Add a TODO list

### ISSUE THREAD

**Issue by JohnDorien1** [ethereum/mix#260]
Helpful for larger contracts > 700 lines.
List all "// TODO ..." and make it "clickable" with jump-to-line action

**Comment by yann300** [comment]
moved to https://github.com/ethereum/remix/issues/87

We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
