### ISSUE TITLE
Add a function browser

### ISSUE THREAD

**Issue by JohnDorien1** [ethereum/mix#263]
Helpful for large contracts. List all available functions with "jump to line" functionality. Sorted alphabetically.

**Comment by yann300** [comment]
moved to https://github.com/ethereum/remix/issues/86

Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
