### ISSUE TITLE
Mix IDE install removing unity packages and ubuntu desktop

### ISSUE THREAD

**Issue by AdamRTomkins** [ethereum/mix#264]
I am getting what seem to be strange messages when I try and install the mix IDE, I stopped the process when I saw that it was removing ubuntu desktop.

Does anyone know why these are being removed?

I am on ubuntu 12.04 following these commands:

sudo add-apt-repository ppa:ethereum/ethereum-qt 
sudo add-apt-repository ppa:ethereum/ethereum 
sudo add-apt-repository ppa:ethereum/ethereum-dev 
sudo apt-get update sudo apt-get install mix 
mix

With the following messages when installing mix

(Reading database ... 176982 files and directories currently installed.) 
Removing appmenu-qt5 (0.3.0+14.04.20140415-0ubuntu1) ... 
Removing ubuntu-desktop (1.325) ... 
Removing checkbox-gui (0.17.6-0ubuntu6) ... 
Removing unity-webapps-twitter (2.4.16+14.04.20140324-0ubuntu1) ... 
Removing unity-webapps-common (2.4.17+14.04.20140416-0ubuntu1) ... 
Removing xul-ext-unity (3.0.0+14.04.20140416-0ubuntu1) ... 
Removing xul-ext-websites-integration (2.3.6+13.10.20130920.1-0ubuntu1.1) ... 
Removing libunity-webapps0 (2.5.0~+14.04.20140409-0ubuntu1) ... 
Removing unity-webapps-service (2.5.0~+14.04.20140409-0ubuntu1) ... 
Removing webapp-container (0.23+14.04.20140428-0ubuntu1) ... 
Removing webbrowser-app (0.23+14.04.20140428-0ubuntu1) ... 
Removing qtdeclarative5-ubuntu-ui-extras-browser-plugin:amd64 (0.23+14.04.20140428-0ubuntu1) ...
 Removing unity-webapps-qml (0.1+14.04.20140408-0ubuntu1) ... 
Removing qtdeclarative5-ubuntu-ui-toolkit-plugin:amd64 (0.1.46+14.04.20140408.1-0ubuntu1) ... 
Removing qtdeclarative5-qtfeedback-plugin:amd64 (5.0~git20130529-0ubuntu3) ... 
Removing libqt5feedback5:amd64 (5.0~git20130529-0ubuntu3) ... 
Removing libqt5multimedia5:amd64 (5.2.1-0ubuntu5) ... 
Removing libqt5organizer5:amd64 (5.0~git20140203~e0c5eebe-0ubuntu2) ... 
Removing liboxideqt-qmlplugin:amd64 (1.8.4-0ubuntu0.14.04.2) ... 
Removing liboxideqtquick0:amd64 (1.8.4-0ubuntu0.14.04.2) ... 
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ... 
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ... 
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ... 
Rebuilding /usr/share/applications/bamf-2.index... 
Processing triggers for mime-support (3.54ubuntu1.1) ... Processing triggers for hicolor-icon-theme (0.13-1) ... 
XProcessing triggers for libc-bin (2.19-0ubuntu6.6) ... 
Processing triggers for libglib2.0-0:amd64 (2.40.2-0ubuntu1) ... 
W: Operation was interrupted before it could finish

**Comment by yann300** [comment]
which command gives you this?
is this sudo apt-get update?
In this case I don't think this is mix related ... I think I just tried to update old package.

**Comment by AdamRTomkins** [comment]
sudo apt-get install mix causes the removes to start. The previous commands complete fine.

**Comment by yann300** [comment]
if you install something else than Mix do you have the same behavior?

**Comment by yann300** [comment]
I close. please reopen if necessary
