### ISSUE TITLE
crash on start when using prebuild binaries (EL CAPITAN)

### ISSUE THREAD

**Issue by LianaHus** [ethereum/mix#265]
moved from cpp-ethereum repo. https://github.com/ethereum/cpp-ethereum/issues/2996

**Comment by fzzr-** [comment]
Have the same issue :(

**Comment by bobsummerwill** [comment]
Closed as dupe of "The Heisenbug" - https://github.com/ethereum/webthree-umbrella/issues/565.   We can reopen if we later find there is anything unique here.
