### ISSUE TITLE
Mix crash on startup: zygote_linux.cc(391) Failed to synchronise with parent zygote process

### ISSUE THREAD

**Issue by salsa-dev** [ethereum/mix#267]
Hi! I'm a laptop running KUBUNTU 15.10 (after an upgrade from 14.04).
`Linux devops 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
I have installed `ethereum, cpp-ethereum, mix` from

```
http://ppa.launchpad.net/ethereum/ethereum/ubuntu wily main
http://ppa.launchpad.net/ethereum/ethereum-dev/ubuntu wily main
```

When starting Mix from the console it crashes with the following: 

```
opergrid@devops:~$ mix

WARNING: This project is using the experimental QML API extensions for QtWebEngine and is therefore tied to a specific QtWebEngine release.
WARNING: The experimental API will change from version to version, or even be removed. You have been warned!

Layout must be attached to Item elements
Layout must be attached to Item elements
[0227/122757:FATAL:zygote_linux.cc(420)] Check failed: len > 0 (-1 vs. 0)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV (core dumped) +++
[0227/122758:FATAL:zygote_linux.cc(391)] Failed to synchronise with parent zygote process

```

The strace log is [here](https://drive.google.com/file/d/0BxiRI5wdbpZWOExWUXlXaDVmYVU/view?usp=sharing) (11Mb).

Could you please have a look into that. Google and the issues on Github has no information on this particular issue but the error in common is connected with Chromium ([zygote_linux.cc](https://chromium.googlesource.com/chromium/chromium/+/master/content/zygote/zygote_linux.cc)).

**Comment by yann300** [comment]
not sure that this is completely related to Mix:
https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8&client=ubuntu#q=FATAL%3Azygote_linux.cc
is Chromium is working normally?

**Comment by salsa-dev** [comment]
Chromium, Chrome are working fine. I have no idea how to debug further. I guess there is no such issue on a fresh installation of KUBUNTU 15.10 and it may well be related to an upgrade from 14.04.
Endless similar bug reports on Chromium are not leading anywhere....
Any hints are welcome.

**Comment by salsa-dev** [comment]
I made a fresh install of KUBUNTU 15.10 on virtual machine and installed mix from the ethereum-dev repository. The problem persists the same.

**Comment by salsa-dev** [comment]
Upgraded to KUBUNTU 16.04. The issue is not any more relevant.
