### ISSUE TITLE
Mix IDe crashes..

### ISSUE THREAD

**Issue by adarshsunil** [ethereum/mix#269]
When trying to open MIX IDE, it crashes with this error:

QOpenGLShaderProgram::uniformLocation( matrix ): shader program is not linked
QOpenGLShaderProgram::uniformLocation( opacity ): shader program is not linked
QOpenGLShaderProgram::uniformLocation( pixelSize ): shader program is not linked
QOpenGLShader::compile(Vertex): failed
QOpenGLShader::compile(Fragment): failed
shader compilation failed: 
""

**Comment by yann300** [comment]
hi
Could you give more detail of the current platform you use?
is this osx or ubuntu?
For now we have a dependency with the opengl library (Qt) so you need to have proper video driver installed.

**Comment by winsvega** [comment]
I had the same issue. Check that your video driver is set up correctly. 
If you using Ubuntu here is what I did

http://forum.ethereum.org/discussion/4060/fixing-amd-video-drivers-on-ubuntu-x64-for-running-mix-and-other-apps#latest

**Comment by yann300** [comment]
@adarshsunil I close. please reopen if you're still having this issue with the video driver updated

**Comment by PranobSamani** [comment]
How to make it work in windows? any  idea
