### ISSUE TITLE
Crash at start (WIN10)

### ISSUE THREAD

**Issue by rfikki** [ethereum/mix#278]
Qt: Untested Windows version 10.0 detected!

WARNING: This project is using the experimental QML API extensions for QtWebEngine and is therefore tied to a specific QtWebEngine release.
WARNING: The experimental API will change from version to version, or even be removed. You have been warned!

Layout must be attached to Item elements
Layout must be attached to Item elements
qml: [{"id":0,"jsonrpc":"2.0","method":"eth_accounts","params":[]}]
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
qrc:/QtQuick/Controls/ScrollView.qml:232:9: QML Binding: Binding loop detected for property "value"
qrc:/QtQuick/Controls/ScrollView.qml:225:9: QML Binding: Binding loop detected for property "value"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredWidth"
  i  17:18:49.230|main  Killing blockchain & extras database (WithExisting::Kill).
  i  17:18:49.258|main  Killing state database (WithExisting::Kill).
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
qml: [{"id":0,"jsonrpc":"2.0","method":"eth_accounts","params":[]}]
qml: [{"id":1,"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}]
  i  17:18:49.320|main  Killing blockchain & extras database (WithExisting::Kill).
  i  17:18:49.336|main  Killing state database (WithExisting::Kill).
  i  17:18:49.395|main  Killing blockchain & extras database (WithExisting::Kill).
  i  17:18:49.409|main  Killing state database (WithExisting::Kill).
qml: Closing project
qml: Loading project at file:///C:/wamp/www/mix-dapp
qrc:///QtQuick/Controls/Private/ScrollBar.qml:98:46: Unable to assign [undefined] to bool
qrc:///QtQuick/Controls/Private/ScrollBar.qml:98:46: Unable to assign [undefined] to bool
qrc:/QtQuick/Controls/TextArea.qml:728:24: Unable to assign [undefined] to QColor
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot read property '__contentHeight' of null
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot read property '__contentHeight' of null
qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:72:42: Unable to assign TextArea_QMLTYPE_121 to TextField_QMLTYPE_160
qrc:///QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read property of null
qrc:///QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read property of null
  i  17:18:49.563|main  Killing blockchain & extras database (WithExisting::Kill).
  i  17:18:49.579|main  Killing state database (WithExisting::Kill).

**Comment by ksank1976** [comment]
similar error in MacOS during Mix-IDE startup.. Anyone can help

**Comment by bobsummerwill** [comment]
Hello again, @ksank1976.

This one is a little trickier, because we don't have a workaround at the moment.   It appears to be specific to Windows 10 (though the failure point looks the same as the other issue), and is likely rooted in our old version of Qt for Windows.

Windows 10 has only been officially supported as of Qt 5.6, and we're still on an older release.   Work is in progress on updating our binaries for this.

Sorry :-(

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
