### ISSUE TITLE
Crash at start (Win 7)

### ISSUE THREAD

**Issue by mburkertt** [ethereum/mix#279]
Hi was installing the Ethereum Windows Package,

when is was trying, the console delivers the following error

![ethereum_mix_errorlog_part1](https://cloud.githubusercontent.com/assets/17721585/13808295/c40758a8-eb65-11e5-97be-880c7d0b0d93.png)
![ethereum_mix_errorlog_part2](https://cloud.githubusercontent.com/assets/17721585/13808296/c40a4bbc-eb65-11e5-82d5-d5b32026016f.png)

For any kind of help, I would be very grateful thank you in advance

Matze

**Comment by gtabmx** [comment]
Same issue for me. On Windows 8.

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
