### ISSUE TITLE
bug on show right view in debug mode

### ISSUE THREAD

**Issue by LianaHus** [ethereum/mix#280]
![screenshot from 2016-03-16 16 02 20](https://cloud.githubusercontent.com/assets/9685356/13816914/80d16058-eb90-11e5-8215-d606ed281030.png)

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
