### ISSUE TITLE
 v1.2.2 Crash at start (WIN10) - probably have a corrupt Trie

### ISSUE THREAD

**Issue by maxxflyer** [ethereum/mix#283]
Just Downloaded 
cpp-ethereum v1.2.2 Windows installer

![16956340](https://cloud.githubusercontent.com/assets/16956340/13980642/06db7a54-f0e0-11e5-93ef-168207ad7085.png)

**Comment by yann300** [comment]
hi! 
We are still working on providing a win10 build.
stay tuned, it will arrive soon.

**Comment by intermension** [comment]
When is that exactly? It's now July... and MS are ending their free Win10 upgrade offer at the end of the month so I will be upgrading before then.

**Comment by chriseth** [comment]
Sorry, due to endless problems with our automation, we are currently switching to a new system. Also, it might potentially be the case that we cannot support mix anymore as part of this switch. We are pushing to get remix in place as soon as possible.

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
