### ISSUE TITLE
/usr/bin/mix (ethereum) binary conflicts with /usr/bin/mix (elixir) binary on *nix systems

### ISSUE THREAD

**Issue by ErikBjare** [ethereum/mix#285]
Was going to install [elixir](http://elixir-lang.org/) on my Arch box today when I, to great surprise, got this error:

```
$ yaourt -S elixir
<normal output>
error: failed to commit transaction (conflicting files)
elixir: /usr/bin/mix exists in filesystem
```

As it turns out, [`mix`](http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html) is _the_ build tool for elixir. So without it, elixir is pretty much unusable.

Confused, I ran `pacman -Qo /usr/bin/mix` and got the answer which is what led me here:

`/usr/bin/mix is owned by ethereum 1.1.3-1`

This was apparently something that bothered me enough to create this issue, I'm not sure what is a reasonable course of action but since elixir/mix existed first, I guess it might be up to the ethereum community to make the move if someone will.

So, just to make _some_ proposal: Perhaps rename the binary to `mixide` or something similar? Might be a good thing to do early on before the inconvenience of changing the executable name becomes overly cumbersome (if it isn't already).

Oh, and I'm very much just assuming this extends to other *nix systems. I haven't actually tested my claim so excuse me if my intuition is misguided.

**Comment by 5chdn** [comment]
Hi @ErikBjare I'm the maintainer of the ArchLinux packages, I could rename the `mix` binary to `mix-ide` or something, but it would be better if this would be done upstream @yann300 @LianaHus --- saying that it would be easier for me if the result of `make` would already yield a `mix-ide` named binary. Would that be possible?

**Comment by andrewlrichardson** [comment]
@ErikBjare I also just got this error yesterday -- any ideas about a fix? :)

**Comment by yann300** [comment]
Yes I guess we should rename it to mix-ide in the build process

**Comment by ErikBjare** [comment]
@yann300 Sounds great!

**Comment by 5chdn** [comment]
@ErikBjare i fixed it for archlinux. try to update. new binary is called `mix-ide`.

still needs to be fixed upstream.

**Comment by chriseth** [comment]
Ubuntu: Fixed for ppa-develop, still need a mechanism to properly upgrade the package.
Windows?
MacOS?
@bobsummerwill

**Comment by bobsummerwill** [comment]
I believe that we're done on this now.
