### ISSUE TITLE
Win7 Ultimate - Mix freezes while browsing files

### ISSUE THREAD

**Issue by maxxflyer** [ethereum/mix#286]
I am working on the index.html , and I click on the contract.sol (or on .mix) and often Mix will freeze. This happens independently by the order I follow clicking the files, pratically I sometimes can modify a file and then save, then I want to modify another one and the application freezes. not sure whether this can help:
(apparently the Sample setValue/getValue is working...)

![immagine](https://cloud.githubusercontent.com/assets/16956340/14021150/93790184-f1da-11e5-84f3-f8c89e27aac1.png)

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
