### ISSUE TITLE
Import of libraries or other contracts don't seem to work

### ISSUE THREAD

**Issue by wdudek** [ethereum/mix#290]
Working in the MIX environment, I'd like to try using a libraries and contracts defined in different files.  However, the main contract always gets an error from MIX, no matter how I define the "import".  The error is:

```
      C:/TryImport/MainContract.sol Error: Source not found: File not supplied initially.
```

> **File someLib.sol**
> 
> > library someLib {...}
> 
> **File MainContract.sol**
> 
> > import "someLib"
> > 
> > contract MainContract {}

**Comment by wdudek** [comment]
using on Win7

**Comment by wdudek** [comment]
Running on Win7.
Sorry, closed by mistake...

**Comment by chriseth** [comment]
You have to give the file name, i.e. try `import "./someLib.sol";`

**Comment by wdudek** [comment]
yup, tried that, full path, backslash, double backslash, with extension and without

`import "./anotherLib.sol";`

C:/Dev/Ethereum/Projects/Greeter/contract.sol Error: Source not found: File not supplied initially.

**Comment by yann300** [comment]
which version of Mix are you running?
it works with me on ubuntu. I will check with a windows build.

**Comment by yann300** [comment]
confirmed. this need to be fixed. for now you can use a full path

**Comment by wdudek** [comment]
got it.  Full path _and it is case sensitive_.  thanks

**Comment by phiferd** [comment]
Why was this issue closed?  Providing the full path is not really a solution.  As you can see from the example above, the full path will be something like "C:/Dev/BobsDevFolder/Foo/".  This does not work when you have more than one developer, especially if one dev is on Windows and the other is on a different OS.

**Comment by bobsummerwill** [comment]
@phiferd I'm not sure why the issue was closed on April 12th.

But Mix is now unsupported (https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/) and was removed from the repository as of cpp-ethereum-v1.3.0.   Sorry!

Some alternatives listed at http://solidity.readthedocs.org
