### ISSUE TITLE
QOpenGLShader cannot create shader

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/mix#292]
Originally logged by @haldhar as https://github.com/ethereum/cpp-ethereum/issues/3011.

QOpenGLShader: could not create shader
shader compilation failed:
""
QOpenGLShaderProgram::uniformLocation( matrix ): shader program is not linked
QOpenGLShaderProgram::uniformLocation( color ): shader program is not linked
QOpenGLShaderProgram::uniformLocation( textureScale ): shader program is not lin
ked
QOpenGLShaderProgram::uniformLocation( dpr ): shader program is not linked
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed:
""
QOpenGLShaderProgram::uniformLocation( qt_Matrix ): shader program is not linked

QOpenGLShaderProgram::uniformLocation( opacity ): shader program is not linked
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed:
""
QOpenGLShaderProgram::uniformLocation( qt_Matrix ): shader program is not linked

QOpenGLShaderProgram::uniformLocation( opacity ): shader program is not linked
![error](https://cloud.githubusercontent.com/assets/9881711/14374624/b2e7317a-fd75-11e5-8b9a-cf584c892b65.PNG)

**Comment by yann300** [comment]
@haldhar could you try updating your video driver please?

**Comment by haldhar** [comment]
Sorry no luck

**Comment by bellaj** [comment]
I have the seem issue any solution?
Win 10 and the video driver is updated

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
