### ISSUE TITLE
accounts number exceed 9  error.

### ISSUE THREAD

**Issue by btc2nxt** [ethereum/mix#295]
add account exceed 9 will cause  user9 loses its name.
if add one more, let's say user10,  it loses its name and its account change to user1's account.

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
