### ISSUE TITLE
The program can't start because MSVCR120.dll is missing from your computer.

### ISSUE THREAD

**Issue by ghost** [ethereum/mix#298]
![error](https://cloud.githubusercontent.com/assets/1657497/14446197/faacbbba-0018-11e6-9c20-59908f786595.PNG)

I downloaded the windows install for [version 1.2.3](https://github.com/ethereum/webthree-umbrella/releases/tag/v1.2.3) on windows 10. I got this error after trying to launch mix. I re downloaded the release and uninstalled the old code and re installed the new code and it still launches with the same error.

Thoughts?

**Comment by ghost** [comment]
Turns out I just needed to download these [Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784). Frustrating windows 10 :-1:

**Comment by bobsummerwill** [comment]
Yes, @jack-fraser, and we're trying to address that too by caling the Redist installer from our installer.

Glad you found the workaround!

https://github.com/ethereum/webthree-umbrella/issues/387
