### ISSUE TITLE
Mix does not render with RDP to windows

### ISSUE THREAD

**Issue by IamSandipC** [ethereum/mix#302]
1. Mix is installed in a Windows 10 machine.
2. I can open it properly in that machine.
3. But when I try to open it from another windows 10 machine using RDP, it does not render. I see white screen. 

QOpenGLShader: could not create shade

This is probably because RDP display driver does not support the graphics requirement. This is an issue since I can not rent a VM in cloud and work on it and run Mix..

**Comment by bobsummerwill** [comment]
I don't know that there is anything which we can about this ourselves, @IamSandipC.

I found some stuff online which you could try?

https://www.google.ca/?ion=1&espv=2#q=windows%20opengl%20over%20rdp

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
