### ISSUE TITLE
mix.dmg upgrade from 1.0.1 --> 1.0.3 unsuccessful 

### ISSUE THREAD

**Issue by inigo-montoya** [ethereum/mix#309]
i've got a version in about that is 1.0.1....downloaded the v1.2.4.dmg release and replaced the .app in applications.

On relaunch the about shows 1.0.1 and I do not have a 1.0.3 functionality (arrow keys in debugger or debugger button at the transaction view)

**Comment by inigo-montoya** [comment]
so it looks like the .app file in the.dmg hasn't been updated since feb 2016.

**Comment by bobsummerwill** [comment]
Hey @inigo-montoyahh!

Yes, we discovered this issue recently - https://github.com/ethereum/webthree-umbrella/issues/496 - so the DMGs for the recent releases have old Mix versions.    The next release will be fixed.

And the development DMG is fine - https://builds.ethereum.org/cpp-binaries-data/develop/Ethereum.dmg.

We won't be going back to fix the old releases.   Please could you try that development release?

The other alternative is Homebrew - http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/osx-homebrew.html

Best wishes, and sorry for the inconvenience.
