### ISSUE TITLE
"New Project" silently deletes project directory

### ISSUE THREAD

**Issue by konradkonrad** [ethereum/mix#311]
### How to reproduce

When I point the "New Project" directory to an existing directory like this:

```
$ pwd
/home/user/code
$ ls -R
.:
testproject

./testproject:
firstcontract.sol  secondcontract.sol
```

Now I create a new project named `testproject` inside `/home/user/code`.
### Actual Outcome

The result is, that all files inside testproject are replaced with `mix`' standard scaffolding files:

```
$ ls -R
.:
testproject

./testproject:
contract.sol  index.html  package

./testproject/package:
compilation

./testproject/package/compilation:
contract.sol.js
```

I.e. my existing files `firstcontract.sol` and `secondcontract.sol` got deleted!
### Expected Outcome

IMO this is unexpected behavior for an IDE. It should never delete files without explicit user action (e.g. 'FILE.contextmenu -> DELETE'). In the case of creating a new project over an existing folder it should either: 
- come up with a warning (minimal) or
- merge the standard scaffolding with the existing directory and have confirmations for all conflicting/existing files (better)
### Version information

`{"build":"0.3.2-0/Release-Linux/g++/Interpreter","mix":"Mix 1.0.3","qt":"5.4.1","solidity":"\nSolidity 0.3.2"}`
Installed via ppa on ubuntu 15.04

**Comment by bobsummerwill** [comment]
This looks to be the same issue as https://github.com/ethereum/webthree-umbrella/issues/521, eh?

@chriseth @yann300 @LianaHus This is a pretty catastrophically terrible bug.

CC @o0ragman0o
