### ISSUE TITLE
Windows 10, mix freezes on startup.

### ISSUE THREAD

**Issue by ResourceHog** [ethereum/mix#316]
Mix will start and then will get stuck in a non-responding state in windows 10.

**Comment by ResourceHog** [comment]
in the mix version that comes with 1.2.4 of cpp-ethereum mix will start up normally but will get stuck in a non-responding state when I create a new project. After which mix will no longer start up normally and will hang in a non-responding state.

**Comment by pshenmic** [comment]
This happens to me too(windows 8). After loading up the sample project, it stucks. Windows 8. Any messages from developers? I cant even try to develop dapps. Mix is very unstable. I tried many things, such like deleting, clearing the cache folders, but still

**Comment by pshenmic** [comment]
Is there any debug options? Mix-ide doesnt provide me anything useful. I was thinking this is because of corrupted genesis file, but on my another workstation(windows 7) everything works flawlessly. I cant even run mix in VirtualBox, because of strange dependency to the video-card drivers. Instead of code and browser, it shows me just the black screens(with guest additions and accelerations enabled).

**Comment by DavidBurela** [comment]
This has been an issue for 4+ months now #244 
No one has an update unfortunately.

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
