### ISSUE TITLE
What to do when downloaded

### ISSUE THREAD

**Issue by GuigsEvt** [ethereum/mix#319]
Hi guys, 

I am sure my question can seem pretty stupid for you. But I have some issues installing Mix IDE. 

When I have extracted the folder from the zip file. What am I suppose to do ? Do I need to pass through the command line of Windows ? 

I am usually launching a .exe but it is obviously not the case here... 

Thanks for the help.

**Comment by bobsummerwill** [comment]
Hey, @GuigsEvt!
The Windows ZIP only contains the `eth` tool.

If you want Mix, you need to run the installer.
https://github.com/ethereum/webthree-umbrella/releases/download/v1.2.8/cpp-ethereum-windows-v1.2.8.exe

Best wishes!

**Comment by GuigsEvt** [comment]
Thanks bob, 

Would I need to incorporate them to Mix when I'll install it ?

**Comment by bobsummerwill** [comment]
Incorporate what?    The ZIP content?   No.

The installer contains a copy of `eth` too.    Best wishes!

**Comment by GuigsEvt** [comment]
Ok thanks. 

Best wishes.
