### ISSUE TITLE
Crash after "Rebuild Scenario"

### ISSUE THREAD

**Issue by PlasmaPower** [ethereum/mix#322]
I get a crash after clicking the "Rebuild Scenario" button. The console log ends with this:

```
<Unknown File>: Can't assign to existing role 'logs' of different type [QObject -> List]
[1]    21187 segmentation fault (core dumped)  mix-ide
```

I made sure to rebuild ethereum without stripping symbols, but it still has "Unknown File". Overall this project seems to be very unstable on my system. I've also encountered various other crashes, but could not reproduce them.

Side note: is there a way to view the ETH balances of contracts?

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.

**Comment by PlasmaPower** [comment]
You might want to disable the issue tracker and add a note in large text to the README. Thanks!
