### ISSUE TITLE
Segfaults on Ubuntu 16.04

### ISSUE THREAD

**Issue by smoove** [ethereum/mix#325]
I have installed mix-ide according to this guide: https://gavofyork.gitbooks.io/turboethereum/content/chapter1.html

When i start mix-ide in 80% of the cases it immediately segfaults.

> kernel: [ 7835.014493] mix-ide[14406]: segfault at 7f394efd93b8 ip 00007f3b465597f1 sp 00007fffb6e10370 error 4 in libQt5Qml.so.5.5.1[7f3b463b1000+40e000]

Sometimes i can start the ide, but after writing a few lines of code it crashes with the same message.

Any help would be greatly appreciated.

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
