### ISSUE TITLE
New Contracts don't appear in add transaction scree,

### ISSUE THREAD

**Issue by hansvde** [ethereum/mix#328]
A newly defined contract can't be used. When I want to create the contract/transaction it is not visible. Only Sample is visible.
I have the idea that deploying isn't working

Working on Windows10 with version 1.2.9

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
