### ISSUE TITLE
error run mix ide in ubuntu

### ISSUE THREAD

**Issue by tegarkurniawan** [ethereum/mix#330]
install mix in ubuntu success with command sudo apt-get install mix-ide, i run command mix for running mix IDE but i get output error 
[2016/08/24-17:18:00, critical] Error: Cannot parse configuration file!
[2016/08/24-17:18:00, critical] Terminating Programm!

solution to this ?

**Comment by bobsummerwill** [comment]
Sorry, but Mix has been discontinued.

We are now focusing on remix ( https://github.com/ethereum/remix ) which will we hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.

Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 

But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.

Thanks and i hope you will enjoy playing with remix! 

Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.

Some other alternatives listed at http://solidity.readthedocs.org
