### ISSUE TITLE
Enum as output parameter return empty bytes array

### ISSUE THREAD

**Issue by gavofyork** [ethereum/mix#5]
https://github.com/ethereum/cpp-ethereum/issues/2570

**Comment by yann300** [comment]
Mix is working with the current behavior (output data returns arrays of empty values instead of 0 values).  The issue is with the return value of the ExecutionResult. 
Maybe this should be moved elsewhere @arkpar  (solidity repo)?

**Comment by LianaHus** [comment]
this could be the same problem as here https://github.com/ethereum/solidity/issues/23 I'm creating this reference here for now.

**Comment by LianaHus** [comment]
I've created the test. The result vector is not empty. we have 32 size array of bytes with 0 values. The values aren't empty but 0.
