### ISSUE TITLE
Make new transaction by default rebuild

### ISSUE THREAD

**Issue by kaeptnjoda** [ethereum/mix#52]
Currently new transactions won't be re-executed when a scenario is rebuild. By default, they should be re-executed. 

--- Changed my mind on this one ;-)

**Comment by yann300** [comment]
even if this is a tx created by the javascript API? cause in that case this tx is more part of the testing part and maybe should not be kept after rebuilding... if it is kept, it will lead to the execution of the same tx twice (one time cause we kept it in the bc model, and one another time by the frontend).
