### ISSUE TITLE
Ether balance in transaction receipt shows initial balance of sender account and final balance for recipient account

### ISSUE THREAD

**Issue by kaeptnjoda** [ethereum/mix#57]
Below transactions send 300 ether from account 06f3c479dd6f0cc08ca2746314d67f9d0843dfdd with intial balance of 1000 ether to account ada582cad256e5f76786551958aba5bf74b8390b with inital balance of 300 ether

![image](https://cloud.githubusercontent.com/assets/8157688/9685089/479038bc-531c-11e5-8c1e-b36c2c9c15ca.png)

**Comment by yann300** [comment]
could you check once https://github.com/ethereum/mix/pull/59 is merged?
