### ISSUE TITLE
 libscrypt.so: cannot open shared object file

### ISSUE THREAD

**Issue by ethers** [ethereum/mix#60]
2adf3a6

built mix successfully and then `cd mix` and `./mix` gives error:

```
./mix: error while loading shared libraries: libscrypt.so: cannot open shared object file: No such file or directory
```

**Comment by yann300** [comment]
have you rebuild the cpp-ethereum repository? building steps have changed a bit:
https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Ubuntu

**Comment by ethers** [comment]
yes, i built all of them in order successfully [except for alethzero which didn't build].  So Mix built 100% success and it is this runtime error...

**Comment by yann300** [comment]
could you check if libscrypt.so is on the libscrypt folder of the build directory of cpp-ethereum?
thanks

**Comment by ethers** [comment]
yes it is there in build directory of cpp-ethereum:   `libscrypt/libscrypt.so`

**Comment by yann300** [comment]
could you run ldconfig -v and copy/paste the output please?

**Comment by ethers** [comment]
i'll close this for now as there are new build steps i need to try.  thanks
