### ISSUE TITLE
Every successful compile (typically at every keystroke) is resetting focus on Windows 7.

### ISSUE THREAD

**Issue by acvanzant** [ethereum/mix#77]
It seems that every successful compile of a contract is resulting in my focus to be reset. This results in my having to click to place my cursor in the contract after each keystroke.

The command prompt repeats the following message each time this happens.

i   11:41:09 | main   Closing blockchain DB
i   11:41:09 | main   Killing blockchain & extras database (WithExisting::KIll).
i   11:41:09 | main   Opened blockchain DB. Latest: #f53e0911... (rebuild not needed)

**Comment by yann300** [comment]
thanks for the report. should be fixed in develop. I close this issue, please repoen if still not working for you.
